/**
 * ─── The recording checklist ────────────────────────────────────────────────
 *
 *   pnpm voice-over:todo              # German — the manuscript's own language
 *   VO_LOCALE=en pnpm voice-over:todo # English
 *
 * Writes `voice-over-todo.md`: every registered spoken line (`src/voice/`),
 * grouped by speaker, in registration order, with a checkbox that ticks
 * itself the moment the matching `.ogg` exists on disk.
 *
 * ── This is a document for a person, not a report for a build ───────────────
 *
 * The point of it is that somebody sits down at a microphone with it open and
 * reads. So it shows, per line, the four things that makes possible: the LINE_ID
 * (which is the filename), the text **in the language being recorded**, the
 * exact path to drop the file at, and — as a section heading — who is speaking.
 *
 * The version this was ported from printed the English text no matter which
 * locale it was checking, which for a German recording session is worse than
 * printing nothing: it looks like the line to read. Here the text follows
 * `VO_LOCALE`, and `VO_LOCALE` defaults to **German**, because the German is the
 * author's own and the English is a translation of it.
 *
 * ── Run under vitest, but it is not a test ──────────────────────────────────
 *
 * `vitest run --config scripts/voiceover.vitest.config.ts` is the cheapest way
 * to get TypeScript, the `@/` alias and ESM in one command without adding a
 * build step or a dependency. It is a generator wearing a `test()`.
 */
import { existsSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { test } from 'vitest'
import { VOICE_ALIASES } from '@/voice/voices'
import {
  collectVoiceLines,
  modelFor,
  nameFor,
  oggPathFlat,
  oggPathNested,
  textFor,
  type VoiceLine
} from './lib/voiceLines'

/** German by default. See the header. */
const LOCALE = (process.env.VO_LOCALE || 'de').trim().toLowerCase()
const ROOT = process.cwd()
const OUT = resolve(ROOT, 'voice-over-todo.md')

/**
 * A line counts as recorded if its `.ogg` sits in EITHER the speaker's folder or
 * the flat locale folder — both are places the runtime looks, so both must tick
 * the box. A checklist that says "not recorded" about a file that plays is the
 * fastest way to get somebody to record it twice.
 */
const recorded = (line: VoiceLine): boolean =>
  existsSync(resolve(ROOT, oggPathNested(LOCALE, line.folder, line.id))) ||
  existsSync(resolve(ROOT, oggPathFlat(LOCALE, line.id)))

/** Markdown-safe one-liner: no raw newlines, no unescaped table pipes. */
const esc = (text: string): string => text.replace(/\r?\n/g, ' ').replace(/\|/g, '\\|').trim()

/** A registry group id as a scene heading a human can place.
 *  `introCellar` → `Intro cellar`. */
const sceneTitle = (group: string): string =>
  group.replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/^./, c => c.toUpperCase())

test('generate voice-over-todo.md', () => {
  const all = collectVoiceLines().filter(line => !line.nonSpeech)

  // Group by speaker: one section per part, which is how a recording session is
  // actually organised — one person reads everything they say, then the next.
  const bySpeaker = new Map<string, VoiceLine[]>()
  for (const line of all) {
    const bucket = bySpeaker.get(line.speaker)
    if (bucket) {
      bucket.push(line)
    } else {
      bySpeaker.set(line.speaker, [line])
    }
  }

  // Biggest part first. A voice actor booked for an afternoon should see the
  // work that fills it at the top, not after eleven one-line walk-ons.
  const speakers = [...bySpeaker.keys()].sort((a, b) => {
    const diff = (bySpeaker.get(b)?.length ?? 0) - (bySpeaker.get(a)?.length ?? 0)
    return diff !== 0 ? diff : a.localeCompare(b)
  })

  const total = all.length
  const done = all.filter(recorded).length
  const out: string[] = []

  out.push('# Voice-over — recording checklist')
  out.push('')
  out.push('> Auto-generated by `pnpm voice-over:todo` — **do not edit by hand** (re-run to refresh).')
  out.push(`> Locale \`${LOCALE}\`  ·  **${done} / ${total}** lines recorded  ·  **${total - done}** to go.`)
  out.push('')
  out.push('**How to record a line.** Say the text below, save it as an `.ogg` named *exactly* after')
  out.push('the `LINE_ID`, and drop it at the path shown. Re-run the command and the box ticks itself.')
  out.push(`Anything in \`public/speech/${LOCALE}/\` flat works too — LINE_IDs are unique — but the`)
  out.push('per-speaker folder keeps one voice in one place.')
  out.push('')
  out.push('A LINE_ID is `<group>-<hash of the German text>`. It does **not** move when a line is')
  out.push('inserted above it, and it *does* change when the line itself is rewritten — at which point')
  out.push('the old recording is of a sentence the game no longer contains, and the box un-ticks itself')
  out.push('on purpose. See `src/voice/lines.ts`.')
  out.push('')
  out.push(`Locale: run \`VO_LOCALE=en pnpm voice-over:todo\` for the English list. The TTS placeholder`)
  out.push('voice named per section comes from `src/voice/voices.ts` and is what plays until a')
  out.push('real recording lands on top of it.')
  out.push('')

  // ── Parts that are one person under two names ────────────────────────────
  //
  // Read off `VOICE_ALIASES` rather than inferred from matching models: German
  // is a six-voice catalogue, unrelated characters share rows on purpose, and an
  // inference would tell a performer two strangers are one person because their
  // placeholder happens to be. Filtered to parts that actually
  // have lines, so a pair only appears when both halves are on the list.
  const aliasGroups = VOICE_ALIASES.map(group => group.filter(who => bySpeaker.has(who))).filter(
    group => group.length > 1
  )
  if (aliasGroups.length) {
    out.push('**One part, two names.** Each row below is a single person with two speaker ids, so one')
    out.push('performer records both sections in one sitting.')
    out.push('')
    for (const group of aliasGroups) {
      const names = group.map(who => {
        const first = bySpeaker.get(who)?.[0] as VoiceLine
        return `\`${who}\` (${esc(nameFor(first, LOCALE))}, ${bySpeaker.get(who)?.length})`
      })
      out.push(`- ${names.join('  ·  ')}`)
    }
    out.push('')
  }

  // ── Summary, so "how much is left" is one glance and not a scroll ─────────
  out.push('## Parts')
  out.push('')
  out.push('| Speaker | Lines | Recorded | TTS placeholder |')
  out.push('| --- | ---: | ---: | --- |')
  for (const who of speakers) {
    const lines = bySpeaker.get(who) as VoiceLine[]
    const first = lines[0] as VoiceLine
    const have = lines.filter(recorded).length
    out.push(`| **${esc(nameFor(first, LOCALE))}** \`${who}\` | ${lines.length} | ${have} | \`${modelFor(first, LOCALE) || '—'}\` |`)
  }
  out.push(`| | **${total}** | **${done}** | |`)
  out.push('')

  // ── The parts themselves ─────────────────────────────────────────────────
  for (const who of speakers) {
    const lines = bySpeaker.get(who) as VoiceLine[]
    const first = lines[0] as VoiceLine
    const have = lines.filter(recorded).length
    out.push('---')
    out.push('')
    out.push(`## ${esc(nameFor(first, LOCALE))}  ·  \`${who}\`  ·  ${have}/${lines.length}`)
    out.push('')
    out.push(`<sub>Drop files in \`public/speech/${LOCALE}/${who}/\`  ·  TTS placeholder \`${modelFor(first, LOCALE) || '—'}\`</sub>`)
    out.push('')
    // Scene sub-headings inside the part: an actor needs some context for the
    // line, and the group id is the only context this file can honestly give.
    let scene = ''
    for (const line of lines) {
      if (line.group !== scene) {
        scene = line.group
        out.push(`**${sceneTitle(scene)}**`)
        out.push('')
      }
      const body = `\`${line.id}\` — ${esc(textFor(line, LOCALE))}  ·  \`${oggPathNested(LOCALE, line.folder, line.id)}\``
      out.push(recorded(line) ? `- [x] ~~${body}~~` : `- [ ] ${body}`)
      out.push('')
    }
  }

  writeFileSync(OUT, out.join('\n'), 'utf8')
  // vitest buffers console.log; write straight to stdout so the summary is
  // visible however the runner is invoked.
  process.stdout.write(
    `voice-over-todo.md — locale ${LOCALE} · ${done}/${total} recorded · ${total - done} remaining · ${speakers.length} speaking parts\n`
  )
  for (const who of speakers) {
    const lines = bySpeaker.get(who) as VoiceLine[]
    process.stdout.write(`   ${String(lines.length).padStart(3)}  ${who}\n`)
  }
})
